import Image from "next/image";

import { Employee } from "@/types/employee";

import { formatDate, formatText } from "@/lib/employeeFormat";

type Props = {
  employee: Employee;
};

export default function EmployeePrintCard({ employee }: Props) {
  return (
    <div className="mx-auto max-w-4xl rounded-2xl border border-slate-200 bg-white p-8 text-slate-900 shadow-sm">
      {/* HEADER */}
      <div className="border-b border-slate-200 pb-5 text-center">
        <h1 className="text-3xl font-bold tracking-tight text-slate-900">
          Employee Profile
        </h1>

        <p className="mt-1 text-sm text-slate-500">Official Employee Record</p>
      </div>

      {/* TOP SECTION */}
      <div className="mt-8 flex gap-8">
        {/* IMAGE */}
        <div className="relative h-36 w-36 shrink-0 overflow-hidden rounded-2xl border-4 border-slate-100 bg-slate-100 shadow-sm">
          {employee.profileImage ? (
            <Image
              src={employee.profileImage}
              alt={employee.name}
              fill
              sizes="144px"
              className="object-cover"
            />
          ) : (
            <div className="flex h-full items-center justify-center text-sm text-slate-400">
              No Image
            </div>
          )}
        </div>

        {/* INFO GRID */}
        <div className="grid flex-1 grid-cols-2 gap-4">
          <Info label="Name" value={formatText(employee.name)} />

          <Info label="Father Name" value={formatText(employee.fatherName)} />

          <Info label="CNIC" value={employee.cnic} />

          <Info label="Birth Date" value={formatDate(employee.birthDate)} />

          <Info label="Primary Phone" value={employee.phone1} />

          <Info label="Secondary Phone" value={employee.phone2 || "N/A"} />

          <Info label="Education" value={formatText(employee.education)} />

          <Info label="Designation" value={formatText(employee.designation)} />

          <Info label="Age" value={`${employee.age} Years`} />

          <Info label="Status" value={formatText(employee.status)} />

          <Info label="Entry Date" value={formatDate(employee.entryDate)} />

          <Info
            label="Exit Date"
            value={
              employee.exitDate
                ? formatDate(employee.exitDate)
                : "Currently Working"
            }
          />

          <div className="col-span-2">
            <Info label="Address" value={employee.address} />
          </div>

          <div className="col-span-2">
            <Info label="Reference" value={employee.reference || "N/A"} />
          </div>
        </div>
      </div>

      {/* FOOTER */}
      <div className="mt-8 flex items-center justify-between border-t border-slate-200 pt-4 text-xs text-slate-500">
        <span>Employee ID: {employee._id}</span>

        <span>Generated by Employee Management System</span>
      </div>
    </div>
  );
}

function Info({ label, value }: { label: string; value?: string }) {
  return (
    <div className="rounded-xl border border-slate-200 bg-slate-50 px-4 py-3">
      <p className="text-[11px] font-semibold uppercase tracking-wide text-slate-500">
        {label}
      </p>

      <p className="mt-1 break-words text-sm font-semibold text-slate-900">
        {value || "N/A"}
      </p>
    </div>
  );
}
