// src/utils/employeeContacts.js
//
// Canonical structure:
//
// emergencyContacts: [
//   {
//     name,
//     relation,
//     contact,
//     address,
//     isPrimary
//   }
// ]
//
// references: [
//   {
//     name,
//     relation,
//     contact,
//     address
//   }
// ]
//
// Legacy fields:
//   phone2    -> emergencyContacts[0].contact
//   reference -> references[0].name
//
// phone2 and reference must NEVER be persisted by normal application logic.

const badRequest = (message) => {
  const error = new Error(message);
  error.statusCode = 400;
  return error;
};

// ============================================================
// General helpers
// ============================================================

const has = (obj, key) =>
  Object.prototype.hasOwnProperty.call(obj, key);

const isBlank = (value) =>
  value === undefined ||
  value === null ||
  (typeof value === "string" && value.trim() === "");

const cleanText = (value, field) => {
  if (value === undefined || value === null) return "";

  if (typeof value !== "string") {
    throw badRequest(`${field} must be a string`);
  }

  return value.trim();
};

const parseBoolean = (value, field) => {
  if (value === undefined || value === null || value === "") {
    return false;
  }

  if (value === true || value === "true") {
    return true;
  }

  if (value === false || value === "false") {
    return false;
  }

  throw badRequest(`${field} must be a boolean`);
};

// ============================================================
// Parse contact arrays
// ============================================================

const parseContactArray = (value, field) => {
  if (value === null || value === undefined) {
    return [];
  }

  // Support JSON strings in multipart/form-data requests.
  if (typeof value === "string") {
    try {
      value = JSON.parse(value);
    } catch {
      throw badRequest(`${field} must be a valid JSON array`);
    }
  }

  if (value === null || value === undefined) {
    return [];
  }

  if (!Array.isArray(value)) {
    throw badRequest(`${field} must be an array`);
  }

  return value.map((entry) => {
    if (
      !entry ||
      typeof entry !== "object" ||
      Array.isArray(entry)
    ) {
      throw badRequest(`Each ${field} entry must be an object`);
    }

    return entry;
  });
};

// ============================================================
// Normalize employee contacts
// ============================================================

const isBlankEntry = (contact) =>
  !contact.name &&
  !contact.relation &&
  !contact.contact &&
  !contact.address;

const normalizeContacts = (
  value,
  field,
  normalizePhone,
  emergency = false,
) => {
  const items = parseContactArray(value, field)
    .map((entry) => {
      const rawContact = cleanText(
        entry.contact,
        `${field}.contact`,
      );

      const normalized = {
        name: cleanText(
          entry.name,
          `${field}.name`,
        ),

        relation: cleanText(
          entry.relation,
          `${field}.relation`,
        ),

        contact: rawContact
          ? normalizePhone(rawContact)
          : "",

        address: cleanText(
          entry.address,
          `${field}.address`,
        ),
      };

      if (emergency) {
        normalized.isPrimary = parseBoolean(
          entry.isPrimary,
          `${field}.isPrimary`,
        );
      }

      return normalized;
    })
    // Ignore completely empty rows generated by forms.
    .filter((contact) => !isBlankEntry(contact));

  // Only one emergency contact can be primary.
  if (
    emergency &&
    items.filter((contact) => contact.isPrimary).length > 1
  ) {
    throw badRequest(
      `${field} can have at most one primary contact`,
    );
  }

  return items;
};

// ============================================================
// Public normalizer
// ============================================================

export const normalizeEmployeeContactData = (
  data = {},
  normalizePhone = (value) => value,
) => {
  const normalized = { ...data };

  // ----------------------------------------------------------
  // Legacy fields must never be written by the application.
  // ----------------------------------------------------------

  delete normalized.phone2;
  delete normalized.reference;

  // ----------------------------------------------------------
  // Emergency contacts
  // ----------------------------------------------------------

  if (normalized.emergencyContacts !== undefined) {
    normalized.emergencyContacts = normalizeContacts(
      normalized.emergencyContacts,
      "emergencyContacts",
      normalizePhone,
      true,
    );
  }

  // ----------------------------------------------------------
  // References
  // ----------------------------------------------------------

  if (normalized.references !== undefined) {
    normalized.references = normalizeContacts(
      normalized.references,
      "references",
      normalizePhone,
      false,
    );
  }

  return normalized;
};

// ============================================================
// Migration helpers
// ============================================================

const digits = (value) =>
  String(value ?? "").replace(/\D/g, "");

const samePhone = (a, b) => {
  const first = digits(a);
  const second = digits(b);

  if (first && second) {
    return first === second;
  }

  return (
    String(a ?? "").trim() ===
    String(b ?? "").trim()
  );
};

const sameName = (a, b) =>
  String(a ?? "")
    .trim()
    .toLowerCase() ===
  String(b ?? "")
    .trim()
    .toLowerCase();

const legacyToString = (legacy) => {
  if (typeof legacy === "string") {
    return legacy.trim();
  }

  if (
    typeof legacy === "number" &&
    Number.isFinite(legacy)
  ) {
    return String(legacy);
  }

  return null;
};

// ============================================================
// Plan migration for one field
// ============================================================

const planField = ({
  employee,
  field,
  legacyField,
  buildEntry,
  matches,
}) => {
  const existing = employee[field];

  // Existing new field must be an array.
  if (
    existing !== undefined &&
    existing !== null &&
    !Array.isArray(existing)
  ) {
    return {
      conflict: `${field} exists but is not an array (left untouched)`,
    };
  }

  const $set = {};
  const $unset = {};

  // Missing/null target becomes an empty array.
  let target = Array.isArray(existing)
    ? existing
    : null;

  if (!target) {
    target = [];
    $set[field] = [];
  }

  // ----------------------------------------------------------
  // No legacy field
  // ----------------------------------------------------------

  if (!has(employee, legacyField)) {
    return {
      $set,
      $unset,
    };
  }

  const legacy = employee[legacyField];

  // ----------------------------------------------------------
  // Legacy field exists but is empty
  // ----------------------------------------------------------

  if (isBlank(legacy)) {
    $unset[legacyField] = "";

    return {
      $set,
      $unset,
    };
  }

  // ----------------------------------------------------------
  // Validate legacy value
  // ----------------------------------------------------------

  const value = legacyToString(legacy);

  if (value === null) {
    return {
      conflict: `${legacyField} has an unsupported type (kept)`,
    };
  }

  // ----------------------------------------------------------
  // Target has no entries
  // ----------------------------------------------------------

  if (target.length === 0) {
    $set[field] = [buildEntry(value)];
    $unset[legacyField] = "";

    return {
      $set,
      $unset,
    };
  }

  // ----------------------------------------------------------
  // Legacy value already exists in new array
  // ----------------------------------------------------------

  if (
    target.some(
      (entry) =>
        entry &&
        matches(entry, value),
    )
  ) {
    // Data is already preserved.
    // Only remove the legacy duplicate.
    $unset[legacyField] = "";

    return {
      $set,
      $unset,
    };
  }

  // ----------------------------------------------------------
  // Conflict:
  // New data exists but doesn't match legacy data.
  // NEVER overwrite it automatically.
  // ----------------------------------------------------------

  return {
    conflict:
      `${legacyField} differs from existing ${field}; ` +
      `not overwritten (kept)`,
  };
};

// ============================================================
// Migration planner
// ============================================================

export const planLegacyContactMigration = (
  employee = {},
) => {
  const results = [
    // --------------------------------------------------------
    // phone2 -> emergencyContacts[0].contact
    // --------------------------------------------------------

    planField({
      employee,
      field: "emergencyContacts",
      legacyField: "phone2",

      buildEntry: (contact) => ({
        name: "",
        relation: "",
        contact,
        address: "",
        isPrimary: true,
      }),

      matches: (entry, value) =>
        samePhone(entry.contact, value),
    }),

    // --------------------------------------------------------
    // reference -> references[0].name
    // --------------------------------------------------------

    planField({
      employee,
      field: "references",
      legacyField: "reference",

      buildEntry: (name) => ({
        name,
        relation: "",
        contact: "",
        address: "",
      }),

      matches: (entry, value) =>
        sameName(entry.name, value),
    }),
  ];

  const conflicts = results
    .filter((result) => result.conflict)
    .map((result) => result.conflict);

  const $set = {};
  const $unset = {};

  // If there is a conflict, don't partially migrate that employee.
  if (conflicts.length === 0) {
    for (const result of results) {
      Object.assign($set, result.$set);
      Object.assign($unset, result.$unset);
    }
  }

  return {
    $set,
    $unset,
    conflicts,

    needsChange:
      Object.keys($set).length > 0 ||
      Object.keys($unset).length > 0,
  };
};